"""add user_interactions table

Revision ID: 045c715cd7fc
Revises: c3d4e5f6a7b8
Create Date: 2026-03-23 10:14:56.282684
"""

from alembic import op
import sqlalchemy as sa


revision = '045c715cd7fc'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interactions_product_id'), 'user_interactions', ['product_id'], unique=False)
    op.create_index('ix_user_interactions_user_action_time', 'user_interactions', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_interactions_user_id'), 'user_interactions', ['user_id'], unique=False)
    op.create_index('ix_user_interactions_user_product', 'user_interactions', ['user_id', 'product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_interactions_user_product', table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_user_id'), table_name='user_interactions')
    op.drop_index('ix_user_interactions_user_action_time', table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_product_id'), table_name='user_interactions')
    op.drop_table('user_interactions')
    # ### end Alembic commands ###
